repos:
  - repo: local
    hooks: 
      - id: linter
        name: linter
        entry: |
          black .
        language: system
        types: [python]

      - id: run-code-coverage
        name: Run Code Coverage
        entry: |
          coverage run manage.py test
        language: system
        pass_filenames: false
        types: [python]

      - id: create-coverage-badge
        name: Create coverage badge
        entry: |
          coverage-badge -f -o coverage/coverage.svg
        language: system
        pass_filenames: false
        types: [python]